# Site settings
title: Библиотека Алисы Фрай
markdown: kramdown
permalink: /books/:year/:month/:day/:title

email: frayalisia@gmail.com

# Social settings
facebook_url: https://www.facebook.com/vikki.tsygankova
instagram_url: https://www.instagram.com/miss_vixy/
github_url: https://github.com/frayalisia/
vk_url: https://vk.com/id197828866
telegram_url: https://t.me/miss_vixy

sass:
  style: compressed
